import os
from typing import List, Dict, Any, Optional
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
from langchain_community.vectorstores import FAISS
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_openai import OpenAIEmbeddings

# Define local database storage path
DB_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "db")
os.makedirs(DB_DIR, exist_ok=True)

def get_embeddings(provider: str, api_key: Optional[str] = None):
    """
    Instantiates the appropriate LangChain embeddings model.
    """
    provider = provider.lower()
    
    if provider == "gemini":
        key = api_key or os.getenv("GEMINI_API_KEY")
        if not key:
            raise ValueError("Gemini API Key is missing. Please configure it in Settings or .env")
        return GoogleGenerativeAIEmbeddings(
            model="models/gemini-embedding-001",
            google_api_key=key
        )
        
    elif provider == "openai":
        key = api_key or os.getenv("OPENAI_API_KEY")
        if not key:
            raise ValueError("OpenAI API Key is missing. Please configure it in Settings or .env")
        return OpenAIEmbeddings(
            model="text-embedding-3-small",
            api_key=key
        )
    else:
        raise ValueError(f"Unsupported provider: {provider}")

def create_vector_store(
    doc_id: str, 
    pages: List[Dict[str, Any]], 
    provider: str = "gemini", 
    api_key: Optional[str] = None
) -> str:
    """
    Splits text into chunks, computes embeddings, and saves a local FAISS index.
    
    Returns:
        str: Absolute path to the saved index directory.
    """
    embeddings = get_embeddings(provider, api_key)
    
    # 1. Convert pages into LangChain Document objects
    documents = []
    for page in pages:
        # Avoid empty pages
        if not page["text"].strip():
            continue
        documents.append(
            Document(
                page_content=page["text"],
                metadata={"page_number": page["page_number"]}
            )
        )
        
    # 2. Chunk documents semantically
    # Chunk size 1000 and overlap 200 provides good balance of context and granularity
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200,
        length_function=len
    )
    chunks = text_splitter.split_documents(documents)
    
    if not chunks:
        raise ValueError("The uploaded document does not contain extractable text chunks.")
        
    # 3. Create FAISS index and save locally
    db_path = os.path.join(DB_DIR, doc_id)
    db = FAISS.from_documents(chunks, embeddings)
    db.save_local(db_path)
    
    return db_path

def retrieve_context(
    doc_id: str, 
    query: str, 
    provider: str = "gemini", 
    api_key: Optional[str] = None,
    k: int = 5
) -> List[Dict[str, Any]]:
    """
    Loads local FAISS index and performs similarity search.
    
    Returns:
        List[Dict]: List of relevant chunks, each with 'text' and 'page_number'.
    """
    embeddings = get_embeddings(provider, api_key)
    db_path = os.path.join(DB_DIR, doc_id)
    
    if not os.path.exists(db_path):
        raise FileNotFoundError(f"Vector store not found for document {doc_id}")
        
    # Load index (allowing dangerous deserialization since it's locally generated by our system)
    db = FAISS.load_local(db_path, embeddings, allow_dangerous_deserialization=True)
    
    # Perform similarity search
    docs = db.similarity_search(query, k=k)
    
    # Format results
    context_chunks = []
    for doc in docs:
        context_chunks.append({
            "text": doc.page_content,
            "page_number": doc.metadata.get("page_number", 1)
        })
        
    return context_chunks
